import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Iris Villa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Iris Villa</h1>
        <div>
          <Link href="./arrival">入山手順</Link>
        </div>
        <div>
          <Link href="./leaving">下山手順</Link>
        </div>
        <div>
          <h1>連絡先一覧</h1>
          <ul>
            <li>管理事務所</li>
            <li>オーナー</li>
            <li>近くの病院</li>
            <li>
              アイリスヴィラの住所: 501-5303 岐阜県郡上市高鷲町大鷲3330-282,
              416, 310 アイリスヴィラ
            </li>
          </ul>
        </div>
      </main>
    </>
  );
}
